export const COLOMBIAN_CAR_BRANDS = [
  "Chevrolet",
  "Renault",
  "Mazda",
  "Toyota",
  "Kia",
  "Hyundai",
  "Nissan",
  "Suzuki",
  "Volkswagen",
  "Ford",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Honda",
  "Mitsubishi",
  "Peugeot",
  "Jeep",
  "Fiat",
  "Changan",
  "JAC",
  "Foton",
  "Great Wall",
  "BYD",
  "Volvo",
  "Subaru",
  "Cupra",
  "SEAT",
  "Opel"
] as const;

export type CarBrand = typeof COLOMBIAN_CAR_BRANDS[number];

export const BRAND_MODELS_MAP: Record<CarBrand, string[]> = {
  Chevrolet: ["Onix", "Tracker", "Joy", "Captiva", "Colorado", "Bolt EV", "Equinox", "Trailblazer", "Camaro", "Spark", "Sail", "Beat", "Prisma"],
  Renault: ["Kwid", "Sandero", "Logan", "Stepway", "Duster", "Oroch", "Captur", "Koleos", "Megane", "Clio", "Twingo", "Scenic"],
  Mazda: ["Mazda 2", "Mazda 3", "CX-30", "CX-5", "CX-50", "CX-90", "MX-5", "BT-50", "Mazda 6"],
  Toyota: ["Corolla", "Corolla Cross", "Yaris", "Hilux", "Fortuner", "Prado", "Land Cruiser 300", "RAV4", "4Runner", "Yaris Cross", "SW4"],
  Kia: ["Picanto", "Rio", "Soluto", "Sportage", "Seltos", "Sonet", "Niro", "K3", "Cerato", "Stonic", "Sorento", "EV6"],
  Hyundai: ["HB20", "HB20S", "Tucson", "Creta", "Kona EV", "Venue", "Accent", "Ioniq 5", "Santa Fe", "Elantra"],
  Nissan: ["March", "Versa", "Sentra", "Kicks", "Frontier", "Qashqai", "X-Trail", "Pathfinder", "Leaf"],
  Suzuki: ["Swift", "Vitara", "Jimny", "S-Cross", "Ertiga", "Baleno", "Alto", "Celerio", "Dzire"],
  Volkswagen: ["Gol", "Voyage", "Polo", "Virtus", "T-Cross", "Nivus", "Taos", "Tiguan", "Amarok", "Jetta", "Teramont"],
  Ford: ["Fiesta", "Focus", "EcoSport", "Escape", "Ranger", "Explorer", "F-150", "Bronco Sport", "Mustang", "Edge"],
  BMW: ["Serie 1", "Serie 2", "Serie 3", "Serie 4", "Serie 5", "X1", "X3", "X4", "X5", "X6", "iX3", "i4"],
  "Mercedes-Benz": ["Clase A", "Clase C", "Clase E", "GLA", "GLB", "GLC", "GLE", "GLS", "EQA", "EQB", "EQE"],
  Audi: ["A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron"],
  Honda: ["Civic", "CR-V", "HR-V", "WR-V", "City", "Accord", "Pilot"],
  Mitsubishi: ["L200", "Montero Sport", "Outlander", "ASX", "Eclipse Cross"],
  Peugeot: ["208", "2008", "3008", "5008", "Partner"],
  Jeep: ["Renegade", "Compass", "Commander", "Wrangler", "Grand Cherokee", "Gladiator"],
  Fiat: ["Uno", "Mobi", "Argo", "Cronos", "Pulse", "Fastback", "Toro", "Fiorino", "500"],
  Changan: ["Star 5", "CS15", "CS35 Plus", "CS55 Plus", "Honor", "Alsvin"],
  JAC: ["T6", "T8 Pro", "S2", "S3", "S4", "E10X", "Sunray"],
  Foton: ["Tunland G7", "Tunland V9", "Gratour", "Aumark", "View"],
  "Great Wall": ["Wingle 5", "Wingle 7", "Poer", "Haval H6", "Haval Jolion"],
  BYD: ["Dolphin", "Yuan Plus", "Song Plus DM-i", "Tang EV", "Han EV", "Qin Plus DM-i", "Seagull"],
  Volvo: ["XC40", "XC60", "XC90", "C40 Recharge", "EX30", "EX90"],
  Subaru: ["Impreza", "XV", "Crosstrek", "Forester", "Outback", "WRX"],
  Cupra: ["Formentor", "Leon"],
  SEAT: ["Ibiza", "Arona", "Ateca", "Tarraco", "Leon"],
  Opel: ["Corsa", "Crossland", "Mokka", "Grandland"]
};
